import { dirname, resolve } from 'node:path';

export function renderHostConfig(options) {
  const fail = () => { throw new Error('Invalid host configuration'); };
  for (const key of ['deployment', 'node', 'bootstrapFile', 'runtimeDirectory']) {
    const path = options[key];
    if (typeof path !== 'string' || !/^\/[A-Za-z0-9_./-]+$/u.test(path) || resolve(path) !== path) fail();
  }
  if (!/^[a-z_][a-z0-9_-]*$/u.test(options.user) || typeof options.port !== 'string' ||
      !/^[1-9][0-9]{0,4}$/u.test(options.port) || Number(options.port) > 65535) fail();
  let origin;
  try { origin = new URL(options.appOrigin); } catch { fail(); }
  if (origin.protocol !== 'https:' || origin.origin !== options.appOrigin || origin.username || origin.password ||
      origin.port || !/^[a-z0-9.-]+$/u.test(origin.hostname)) fail();
  const { deployment, node, user, bootstrapFile, runtimeDirectory } = options;
  return {
    unit: `# Generated by Multi Device Context
[Unit]
Description=Multi Device Context
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=${user}
UMask=0077
WorkingDirectory=${deployment}
Environment=PATH=${dirname(node)}:/usr/local/bin:/usr/bin:/bin
Environment=PM2_HOME=${runtimeDirectory}/pm2
Environment=MDC_BOOTSTRAP_FILE=${bootstrapFile}
ExecStart=${node} ${deployment}/node_modules/pm2/bin/pm2-runtime start ${deployment}/config/ecosystem.config.cjs
Restart=always
RestartSec=10
TimeoutStopSec=45
KillMode=control-group
MemoryMax=768M
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
`,
    caddy: `# Generated by Multi Device Context\nhttp://${origin.hostname} {\n  encode zstd gzip\n  # Trust Cloudflare's client IP only from the local tunnel connector.\n  @tunnel {\n    remote_ip 127.0.0.1 ::1\n    header CF-Connecting-IP *\n  }\n  handle @tunnel {\n    reverse_proxy 127.0.0.1:${options.port} {\n      header_up X-Forwarded-For {http.request.header.CF-Connecting-IP}\n    }\n  }\n  handle {\n    reverse_proxy 127.0.0.1:${options.port} {\n      header_up X-Forwarded-For {http.request.remote.host}\n    }\n  }\n}\n`,
  };
}
