import test from 'node:test';
import assert from 'node:assert/strict';
import { renderHostConfig } from './host-config.mjs';
const options = {
  deployment: '/home/example/deploy/multi-device-context', node: '/usr/bin/node', user: 'example',
  bootstrapFile: '/home/example/.config/multi-device-context/bootstrap.json',
  runtimeDirectory: '/home/example/.config/multi-device-context/runtime',
  appOrigin: 'https://context.example.com', port: '8788',
};
test('renders an isolated service and exact app Caddy site', () => {
  const { unit, caddy } = renderHostConfig(options);
  assert.match(unit, /User=example\n/);
  assert.match(unit, /Environment=PM2_HOME=\/home\/example\/\.config\/multi-device-context\/runtime\/pm2\n/);
  assert.match(unit, /node_modules\/pm2\/bin\/pm2-runtime start/);
  assert.match(unit, /UMask=0077/);
  assert.match(unit, /MemoryMax=768M\n/);
  assert.equal(caddy, '# Generated by Multi Device Context\nhttp://context.example.com {\n  encode zstd gzip\n  reverse_proxy 127.0.0.1:8788\n}\n');
  assert.doesNotMatch(unit+caddy, /PRIVATE KEY|AUTH0_API_TOKEN|GOOGLE_APPLICATION_CREDENTIALS/);
});
test('rejects unit/Caddy injection and unsafe paths', () => {
  for (const replacement of [
    { user: 'example\nUser=root' }, { deployment: '/tmp/a\nExecStart=/bin/sh' },
    { node: '/usr/%h/node' }, { bootstrapFile: 'relative.json' },
    { appOrigin: 'https://example.com/path' }, { appOrigin: 'https://x:password@example.com' },
    { port: '8788\n}' }, { port: '65536' },
  ]) assert.throws(() => renderHostConfig({ ...options, ...replacement }), /host configuration/i);
});
